### ISSUE TITLE
Static website pre-renderer 

### ISSUE THREAD

**Issue by tj** [tj/sponsors#1]
In ["Pre-rendering static websites with wget"](https://apex.sh/blog/post/pre-render-wget/) I mentioned how to do this with `wget`, however, a small Go tool could be much more efficient at this, and it would be a cool little project.

Basically you'd start your web app, then run something like:

```
$ static-render http://localhost:3000
```

This would create a static copy of your site — to ./dist by default — ready for deployment.

---

- [x] Basic implementation
- [x] Handling of assets (css, rss, images, etc)
- [x] Follow CSS imports
- [x] Support for rendering 404 pages etc, which are not linked
- [x] Add JSON configuration
- [x] Timeouts
- [x] Benchmark & profile with a huge site
- [x] Add examples
- [x] Add `-C` flag
- [x] Simple static file server for previewing?
- [ ] Add nicer logging and error reporting
- [ ] Final polish
- [ ] Blog post

**Comment by ysm0622** [comment]
It's a bit different, but I saw a similar project [monolith](https://github.com/Y2Z/monolith). Take a look. :)

**Comment by stuartpb** [comment]
I had an idea for a tool like this a while back that I planned to implement in Node.js, called "wjet" - if you implement this in Go, what do you think of calling it "wgot"?

**Comment by tj** [comment]
I have no ideas for a name yet :D but it's more or less working, just need to make it a bit nicer and I'll push a repo

**Comment by tj** [comment]
still needs some polish but here we go! https://github.com/tj/staticgen
