### ISSUE TITLE
Insomnia tracker and management CLI 

### ISSUE THREAD

**Issue by tj** [tj/sponsors#3]
I've had insomnia for years, and haven't found any good trackers which do what I like really, so I would love to have a simple CLI to keep a sleep journal, and calculate sleep restriction, report on results etc.

**Comment by nikitavoloboev** [comment]
> calculate sleep restriction

Why don't you sleep for as much as your body needs? [Why we sleep](https://www.goodreads.com/book/show/34466963-why-we-sleep) is a great book on sleep.

Just curious as there is no time pressure to wake up at a certain time so it's best to get as much sleep as possible (wake up with no alarm) even if there is trouble getting to sleep (insomnia).

**Comment by tj** [comment]
I have "sleep maintenance" issues, so I wake up in the middle of the night really alert, but this sleep restriction stuff is supposed to help train your body/brain to stay asleep without fragmentation. I'm still trying it but apparently it's one of the most effective things!

**Comment by stuartpb** [comment]
I've had good luck with my Pebble watch's sleep tracking - what fitness trackers / smart watches have you tried?

**Comment by tj** [comment]
I think you're right, plenty of devices/apps that are good enough, none seem quite tailored to sleep restriction as a therapy but they're good enough :D
